server:
  port: 9000
  servlet:
    context-path: /api
spring:
  application:
    name: guid-pro
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:guid-pro}
    username: root
    password: great@PassW0RD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:   http://localhost:8082/realms/guidpro
          jwk-set-uri:  http://localhost:8082/realms/guidpro/protocol/openid-connect/certs
  mail:
    host: 192.168.177.1
    port: 1025   # 465
    username: support@guid-pro.com
    password: noPassW0RD
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: true
jwt:
  auth:
      converter:
        resource-id: backend
keycloak:
  realm: guidpro
  adminClientId: backend
  adminClientSecret: 7Fz9BussSr4ajojzKIwoGS4GNBoFNtXP
  client: backend
  urls:
    auth: http://localhost:8082
